services:
  toolarr:
    image: 192.168.45.15:5000/toolarr:build-004
# Option 1: Use environment variables from .env file (recommended)
#    env_file: .env 
    environment:
      TOOL_API_KEY: ${TOOL_API_KEY:-changeme}
      SONARR_INSTANCE_1_NAME: ${SONARR_INSTANCE_1_NAME:-sonarr}
      SONARR_INSTANCE_1_URL: ${SONARR_INSTANCE_1_URL:-http://sonarr:8989}
      SONARR_INSTANCE_1_API_KEY: ${SONARR_INSTANCE_1_API_KEY}
      RADARR_INSTANCE_1_NAME: ${RADARR_INSTANCE_1_NAME:-radarr}
      RADARR_INSTANCE_1_URL: ${RADARR_INSTANCE_1_URL:-http://radarr:7878}
      RADARR_INSTANCE_1_API_KEY: ${RADARR_INSTANCE_1_API_KEY}
    
    # ports:
    #   - "8010:8000"
    
    networks:
      - traefik_public
      
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.toolarr.rule=Host(`toolarr.moderncaveman.us`)"
        - "traefik.http.routers.toolarr.entrypoints=websecure"
        - "traefik.http.services.toolarr.loadbalancer.server.port=8000"
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

networks:
  traefik_public:
    external: true
