version: '3.8'

services:
  toolarr:
    image: 192.168.45.15:5000/toolarr:fix3
    
    # Option 1: Use environment variables from .env file (recommended)
    env_file: .env
    
    # Option 2: Define environment variables inline (uncomment and modify)
    # environment:
    #   TOOL_API_KEY: ${TOOL_API_KEY:-changeme}
    #   SONARR_INSTANCE_1_NAME: ${SONARR_INSTANCE_1_NAME:-sonarr}
    #   SONARR_INSTANCE_1_URL: ${SONARR_INSTANCE_1_URL:-http://sonarr:8989}
    #   SONARR_INSTANCE_1_API_KEY: ${SONARR_INSTANCE_1_API_KEY}
    #   RADARR_INSTANCE_1_NAME: ${RADARR_INSTANCE_1_NAME:-radarr}
    #   RADARR_INSTANCE_1_URL: ${RADARR_INSTANCE_1_URL:-http://radarr:7878}
    #   RADARR_INSTANCE_1_API_KEY: ${RADARR_INSTANCE_1_API_KEY}
    
    # Uncomment to expose the service directly (not needed if using Traefik)
    ports:
      - "8010:8000"
    
    networks:
      - traefik_public
      
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

networks:
  traefik_public:
    external: true
