version: '3.8'

services:
  toolarr:
    # Option 1: Use pre-built image from Docker Hub (replace USERNAME with actual Docker Hub username)
    # image: USERNAME/toolarr:latest
    
    # Option 2: Use pre-built image from GitHub Container Registry
    # image: ghcr.io/USERNAME/toolarr:latest
    
    # Option 3: Build locally (default)
    build: .
    image: toolarr:latest
    
    env_file: .env
    networks:
      - traefik_public
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

networks:
  traefik_public:
    external: true
